### ISSUE TITLE
Match deequ support for spark 3.2.1

### ISSUE THREAD

**Issue by epilif1017a** [awslabs/python-deequ#93]
Deequ now supports Spark 3.2.1. However, pydeequ still did not catch up to spark 3.1.x. 

Goal: update pydeequ to support new deequ version and Spark 3.2.1

**Comment by ghirardinicola** [comment]
Beside not being up to date with deeque version in the packages (pydeequ.deequ_maven_coord)), are there other problems?

**Comment by epilif1017a** [comment]
Hi @ghirardinicola thanks for reaching out :) Honestly we can’t tell, as we are still on Spark 3.1.2 in our framework (holding off to decide if we cut deequ off of the framework or not) and avoiding rolling out the dq part of the framework globally because we don’t want to fork the project internally to keep up with deequ (which for us would be an extra effort). So in 3.1.2 there was for us the issue of in certain scenarios the Spark app wouldn’t finish automatically if we had pydeequ actions (but we manage to sort that out by manually closing the Spark context gateway (I think you have this on your issue list also, at least I remember seeing an issue). And on 3.2 we did not test yet but I believe there’s issues in your issue list reporting that some analyzers do not work.

therefore it would give the pydeequ user base much more confidence in the project if there was a faster release cycle between Spark versions, deequ and pydeequ. But don’t get me wrong, we all understand that as an open source project the dev team is already kind enough to spend their time to work extra on the project. But I believe because this project and deequ are so cool that their roadmap is very important to potential heavy users like us for example. That’s why we are so interested :)

**Comment by mycaule** [comment]
`ApproxCountDistinct` doesn't work, 

`org.apache.spark.sql.catalyst.expressions.aggregate.AggregateExpression`

**Comment by hashanpasindu** [comment]
does pydeequ ==1.0.1 supports for spark 3.2 ?

**Comment by mycaule** [comment]
yes it also works with spark 3.3 and 3.1

**Comment by hashanpasindu** [comment]
Thanks for the reply. Im trying to use column profiler and 
Im getting 
java.lang.NoSuchMethodError: 'org.apache.spark.sql.catalyst.expressions.aggregate.AggregateExpression. ...
Error
. 
I use pyspark 3.2.1 on databricks and pydeeq 1.0.1.

Is there any worker ?

**Comment by mycaule** [comment]
There isn't, it is the same problem I had above.
You should also have a look at this the release is expected very soon https://github.com/awslabs/python-deequ/issues/93

**Comment by chenliu0831** [comment]
1.1.0 is released with Spark 3.2/3.3 support - I would close this for now
